model: 'ResNet'
pretrained: True
weight_path: '/opt/ml/WorkSpace/level1_imageclassification-cv-20/weights/resnet18-5c106cde.pth'

loss: 'FocalLoss'

optimizer: 'Adam'

epoch: 51
lr: 0.0001
weight_decay: 0.00001
batch_size: 64
data_path: '/opt/ml/input/data/train'

run_name: 'resnet18_pretrained_cutout0.75'